const res = [
  {
    id: 609230195,
    name: 'A-test-repository',
    full_name: 'dobosmarton/A-test-repository',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'This is a test repository',
    url: 'https://api.github.com/repos/dobosmarton/A-test-repository',
    html_url: 'https://github.com/dobosmarton/A-test-repository',
  },
  {
    id: 603468305,
    name: 'boilerplate-mixer',
    full_name: 'dobosmarton/boilerplate-mixer',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/boilerplate-mixer',
    html_url: 'https://github.com/dobosmarton/boilerplate-mixer',
  },
  {
    id: 579649102,
    name: 'next-magic-auth',
    full_name: 'dobosmarton/next-magic-auth',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Authentication with NextJS, Magic Auth and Vercel serverless function',
    url: 'https://api.github.com/repos/dobosmarton/next-magic-auth',
    html_url: 'https://github.com/dobosmarton/next-magic-auth',
  },
  {
    id: 571123389,
    name: 'sst-qwik-app',
    full_name: 'dobosmarton/sst-qwik-app',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Demo application with SST and Qwik',
    url: 'https://api.github.com/repos/dobosmarton/sst-qwik-app',
    html_url: 'https://github.com/dobosmarton/sst-qwik-app',
  },
  {
    id: 517817340,
    name: 'nextjs-sample',
    full_name: 'dobosmarton/nextjs-sample',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Basic Nextjs project',
    url: 'https://api.github.com/repos/dobosmarton/nextjs-sample',
    html_url: 'https://github.com/dobosmarton/nextjs-sample',
  },
  {
    id: 494167940,
    name: 'microservice-demo',
    full_name: 'dobosmarton/microservice-demo',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Demo Microservice Project',
    url: 'https://api.github.com/repos/dobosmarton/microservice-demo',
    html_url: 'https://github.com/dobosmarton/microservice-demo',
  },
  {
    id: 445808322,
    name: 'strapi',
    full_name: 'dobosmarton/strapi',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: '🚀 Open source Node.js Headless CMS to easily build customisable APIs',
    url: 'https://api.github.com/repos/dobosmarton/strapi',
    html_url: 'https://github.com/dobosmarton/strapi',
  },
  {
    id: 443184726,
    name: 'automated-market-maker',
    full_name: 'dobosmarton/automated-market-maker',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Learn how to create an Automated Market Maker',
    url: 'https://api.github.com/repos/dobosmarton/automated-market-maker',
    html_url: 'https://github.com/dobosmarton/automated-market-maker',
  },
  {
    id: 435984427,
    name: 'solana-hooks',
    full_name: 'dobosmarton/solana-hooks',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'React hooks for web3 development on Solana network',
    url: 'https://api.github.com/repos/dobosmarton/solana-hooks',
    html_url: 'https://github.com/dobosmarton/solana-hooks',
  },
  {
    id: 435279130,
    name: 'solana-nft',
    full_name: 'dobosmarton/solana-nft',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Solana NFT minting platform',
    url: 'https://api.github.com/repos/dobosmarton/solana-nft',
    html_url: 'https://github.com/dobosmarton/solana-nft',
  },
  {
    id: 429221865,
    name: 'solana-gif-gallery',
    full_name: 'dobosmarton/solana-gif-gallery',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'GIF gallery application built in Solana blockchain',
    url: 'https://api.github.com/repos/dobosmarton/solana-gif-gallery',
    html_url: 'https://github.com/dobosmarton/solana-gif-gallery',
  },
  {
    id: 423598003,
    name: 'hardhat-box',
    full_name: 'dobosmarton/hardhat-box',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Demo ethereum smart contract project',
    url: 'https://api.github.com/repos/dobosmarton/hardhat-box',
    html_url: 'https://github.com/dobosmarton/hardhat-box',
  },
  {
    id: 378981622,
    name: 'nextjs-browser-encryption',
    full_name: 'dobosmarton/nextjs-browser-encryption',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'NextJS based browser encryption/decryption demo application',
    url: 'https://api.github.com/repos/dobosmarton/nextjs-browser-encryption',
    html_url: 'https://github.com/dobosmarton/nextjs-browser-encryption',
  },
  {
    id: 370420391,
    name: 'dobosmarton',
    full_name: 'dobosmarton/dobosmarton',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/dobosmarton',
    html_url: 'https://github.com/dobosmarton/dobosmarton',
  },
  {
    id: 370406345,
    name: 'healthcare-demo-backend',
    full_name: 'dobosmarton/healthcare-demo-backend',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Healthcare demo backend application with PostgreSQL, Prisma, TypeGraphQL, and Apollo Server',
    url: 'https://api.github.com/repos/dobosmarton/healthcare-demo-backend',
    html_url: 'https://github.com/dobosmarton/healthcare-demo-backend',
  },
  {
    id: 345453448,
    name: 'roommates-landing',
    full_name: 'dobosmarton/roommates-landing',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/roommates-landing',
    html_url: 'https://github.com/dobosmarton/roommates-landing',
  },
  {
    id: 330157125,
    name: 'contentful-test',
    full_name: 'dobosmarton/contentful-test',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/contentful-test',
    html_url: 'https://github.com/dobosmarton/contentful-test',
  },
  {
    id: 315012744,
    name: 'movie-app-graphql',
    full_name: 'dobosmarton/movie-app-graphql',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/movie-app-graphql',
    html_url: 'https://github.com/dobosmarton/movie-app-graphql',
  },
  {
    id: 290762089,
    name: 'movie-app',
    full_name: 'dobosmarton/movie-app',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/movie-app',
    html_url: 'https://github.com/dobosmarton/movie-app',
  },
  {
    id: 290468206,
    name: 'neszmenyi-design-sitebuild',
    full_name: 'dobosmarton/neszmenyi-design-sitebuild',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/neszmenyi-design-sitebuild',
    html_url: 'https://github.com/dobosmarton/neszmenyi-design-sitebuild',
  },
  {
    id: 289647975,
    name: 'neszmenyi-design',
    full_name: 'dobosmarton/neszmenyi-design',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Neszményi Design - Lakberendezés, belsőépítészet, 3D látványtervezés, felújítás.',
    url: 'https://api.github.com/repos/dobosmarton/neszmenyi-design',
    html_url: 'https://github.com/dobosmarton/neszmenyi-design',
  },
  {
    id: 289641792,
    name: 'gatsby-starter-blog',
    full_name: 'dobosmarton/gatsby-starter-blog',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Gatsby starter for creating a blog',
    url: 'https://api.github.com/repos/dobosmarton/gatsby-starter-blog',
    html_url: 'https://github.com/dobosmarton/gatsby-starter-blog',
  },
  {
    id: 286679312,
    name: 'home-renting-landlord',
    full_name: 'dobosmarton/home-renting-landlord',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/home-renting-landlord',
    html_url: 'https://github.com/dobosmarton/home-renting-landlord',
  },
  {
    id: 283971952,
    name: 'portfolio-site',
    full_name: 'dobosmarton/portfolio-site',
    private: true,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'My personal portfolio site',
    url: 'https://api.github.com/repos/dobosmarton/portfolio-site',
    html_url: 'https://github.com/dobosmarton/portfolio-site',
  },
  {
    id: 267326539,
    name: 'react-native-webview-quill',
    full_name: 'dobosmarton/react-native-webview-quill',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/react-native-webview-quill',
    html_url: 'https://github.com/dobosmarton/react-native-webview-quill',
  },
  {
    id: 267264525,
    name: 'react-native-zss-rich-text-editor',
    full_name: 'dobosmarton/react-native-zss-rich-text-editor',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Remove react-native-updated-webview-bridge; use react-native-webview instead',
    url: 'https://api.github.com/repos/dobosmarton/react-native-zss-rich-text-editor',
    html_url: 'https://github.com/dobosmarton/react-native-zss-rich-text-editor',
  },
  {
    id: 253436474,
    name: 'mammoth.js',
    full_name: 'dobosmarton/mammoth.js',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'Convert Word documents (.docx files) to HTML',
    url: 'https://api.github.com/repos/dobosmarton/mammoth.js',
    html_url: 'https://github.com/dobosmarton/mammoth.js',
  },
  {
    id: 250313845,
    name: 'covid',
    full_name: 'dobosmarton/covid',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'COVID-19 data app',
    url: 'https://api.github.com/repos/dobosmarton/covid',
    html_url: 'https://github.com/dobosmarton/covid',
  },
  {
    id: 247524007,
    name: 'gatsby-forestry',
    full_name: 'dobosmarton/gatsby-forestry',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: null,
    url: 'https://api.github.com/repos/dobosmarton/gatsby-forestry',
    html_url: 'https://github.com/dobosmarton/gatsby-forestry',
  },
  {
    id: 237054196,
    name: 'draft-js-utils',
    full_name: 'dobosmarton/draft-js-utils',
    private: false,
    owner: {
      id: 11165169,
      avatar_url: 'https://avatars.githubusercontent.com/u/11165169?v=4',
      url: 'https://api.github.com/users/dobosmarton',
      name: null,
      email: null,
    },
    description: 'DraftJS: import/export ContentState to and from HTML/Markdown',
    url: 'https://api.github.com/repos/dobosmarton/draft-js-utils',
    html_url: 'https://github.com/dobosmarton/draft-js-utils',
  },
];
